name: flutter_test_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  app_settings: ^5.1.1
  device_info_plus: ^9.1.2
  flutter:
    sdk: flutter
  image: ^4.1.7
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  tflite_flutter: ^0.10.4
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/styles/
